MOVEitFileUpload/Models/ErrorViewModel.cs
namespace MOVEitFileUpload.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MOVEitFileUpload/ViewModels/FileUploadViewModel.cs
namespace MOVEitFileUpload.ViewModels;

public class FileUploadViewModel
{
    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public string Url { get; set; } = null!;

    public IFormFile File { get; set; } = null!;
}

MOVEitFileUpload/Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Mvc;
using MOVEitFileUpload.Services.Interfaces;
using MOVEitFileUpload.ViewModels;

using static MOVEitFileUpload.Common.Messages;

namespace MOVEitFileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly IFileUploadService fileUploadService;

        public FileUploadController(IFileUploadService fileUploadService)
        {
            this.fileUploadService = fileUploadService;
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(FileUploadViewModel fileUploadViewModel)
        {
            try
            {
                fileUploadService.ValidateInput(fileUploadViewModel);

                await fileUploadService.UploadFile(fileUploadViewModel);

                ViewData["SuccessMessage"] = SuccessfulyUploadedFile;
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }

            return View();
        }
    }
}

MOVEitFileUpload/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MOVEitFileUpload.Models;

namespace MOVEitFileUpload.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MOVEitFileUpload/Views/FileUpload/Upload.cshtml
@model MOVEitFileUpload.ViewModels.FileUploadViewModel
@{
    ViewData["Title"] = "Upload Page";
}

<h2>Upload Page</h2>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" id="username" name="username" asp-for="Username" required="true"/>
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" asp-for="Password" required="true" />
    </div>

    <div class="form-group">
        <label for="url">URL:</label>
        <input type="text" class="form-control" id="url" name="url" asp-for="Url" placeholder="https://{your-server-name}" required="true" />
    </div>

    <div class="form-group">
        <label for="file">Upload File:</label>
        <input type="file" class="form-control-file" id="file" name="file" asp-for="File" required="true" />
    </div>

    <div>
        @if (ViewData["SuccessMessage"] != null)
        {
            <p style ="color: darkgreen">@ViewData["SuccessMessage"]</p>
        }
        else if (ViewData["ErrorMessage"] != null)
        {
            <p style="color: darkred">@ViewData["ErrorMessage"]</p>
        }
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<style>
    .form-group {
        margin-bottom: 15px;
    }
</style>

MOVEitFileUpload/Views/Home/Index.cshtml
<h2>Welcome to MOVEit File Upload</h2>

<p>Please navigate to 'Upload' to upload a file to your MOVEit server</p>

MOVEitFileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MOVEit File Upload</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MOVEitFileUpload.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MOVEit File Upload</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileUpload" asp-action="Upload">Upload</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MOVEit File Upload
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>